### ISSUE TITLE
ISRs, fraud proofs in Cosmos SDK and deferred execution

### ISSUE THREAD

**Issue by mattdf** [celestiaorg/rollmint#132]
The Cosmos SDK currently has no way to extract ISRs without calling `Commit()` on the on-disk multistore which returns the `CommitID` that represents the state root. The cached multistore that is in `deliverState` contains no `Commit()` function and cannot be used to extract a state root. One can force committing `deliverState` to the multistore after each `DeliverTx` call, but this might have unintended consequences in the flow of the sdk context, as the main `deliverState` multistore is never written to until `Commit()`. It would also be I/O heavy in the current implementation to call that on every transaction.

To "cleanly" add ISRs to the chain data would also require a modification of the `ResponseDeliverTx` message which breaks compatibility with tendermint.

Additionally, given that the goal of ISRs is to enable fraud proofs, simply tacking ISRs onto that message achieves nothing, because there will be no way for nodes to actually generate fraud proofs without a significant change in the mechanism of how the SDK is used.

When a transaction is run, the transaction needs to use a state-access interface that creates an accounting of every state access, and state write, and returns that to a higher level context in the case of fraud. Without this state-accounting "wrapper", an execution of `DeliverTx` would either return a transaction failure due to invalid transition, but without any way for the SDK to know at which point the transition was invalid, or would succed in execution but not match the next supplied ISR, and equally the SDK in the general case would not be able to construct a fraud proof without the ability to introspect the state access and writes of a transaction. The SDK provides a `TraceKVStore` that keeps track of writes, but not *accesses*, which are needed to generate fraud proofs.

Given that this kind of state-accounting is required to generate general fraud proofs from the SDK's level, it would be more fruitful to introduce it as a foundational extension to the SDK as a wrapper/base that all rollups on Celestia should use. 

In the case of an EVM-based rollup, given that in the worst case a single transaction can take up an entire block - and hence make the worst-case fraud proof require passing around an entire block's worth of state, "naive" limiting by tx gas severely harms the usability of the rollup (as state access/write will always be far more expensive and limiting overall gas to constrain fraud-proof sizes would set that bound too low). It would be far better to allow VMs/execution environments to interface with the state-accounting wrapper to explicitly set limits on state access and write, rather than relying on the too-general gas mechanic.

Fraud proofs and explicit state-accounting are a new mechanic that cannot be transparently "folded" into blockchains that are not aware of them, as it ends up imposing undue burdens at wrong levels of the execution stack.

A final problem is deferred execution, which makes it such that transactions are not run until the commit phase, and as such makes a lot of error checking and execution bounding impossible that leaves open different DoS vectors. As an example, In an EVM-based rollup, a proposer would not be able to know how much gas a transaction will actually use compared to what it sets as its allowance, and in the most general case the block proposer **CANNOT** fully pre-run this transaction to check how much gas it will actually use - as (example), the rollup may allow a transaction to see the set of validators that signed the committed block, and perform a different operation depending on that set, given that the block is meant to be finalized prior to any full executions taking place.

Deferred execution causes multiple layers of issues, for fraud proofs and for the ability to construct blocks optimally and prevent DoS issues. In an environment with arbitrary VM execution, it is a broken and heavily constraining mechanic that we should avoid accidentally entrenching as much as possible.

**Comment by liamsi** [comment]
While this is an extremely valuable writeup, it is worth noting that Rollups do not really need to follow the deferred execution model. Sequencers are free to call Commit and inject the app hash in the block (with the Txs that resulted in that app hash) _before_ publishing that block on Celestia or in the Rollups sub-network.

**Comment by tzdybal** [comment]
This was very valuable writeup, and helped with implementation.

**Comment by hydrogenbond007** [comment]
🫡
