### ISSUE TITLE
Pass logger config to mockserver

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#363]
Configuration for mockserver is hardcoded in https://github.com/celestiaorg/optimint/blob/tzdybal/latest-cosmos/da/grpc/mockserv/mockserv.go#L18.

It would be great to have a possibility to pass this configuration.

**Comment by randomshinichi** [comment]
The code has changed then, is this issue still relevant?

**Comment by tzdybal** [comment]
This is still relevant - ideally the logger should be passed to `GetServer` instead of creating it inside this function.
Current code location: https://github.com/celestiaorg/rollmint/blob/cc0a2950ea752b8905fb35062069a951c99ef115/da/grpc/mockserv/mockserv.go#L19
