### ISSUE TITLE
Send or Receive ISRs for state transitions over ABCI

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/rollmint#384]
To enable Optimint to check for fraudulent state transitions a node needs to be able to compare the ISRs given to it by the current block producer to those it generates when executing the state transitions itself. The ISRs from the block producer will be given to Optimint in block headers while the generated ISRs will be in the Cosmos-SDK. 

Optimint needs to either give cosmos-sdk the block producer's ISRs or it needs to receive the generated ISRs back from the cosmos-sdk. 

Depends on: 
- [x] https://github.com/celestiaorg/cosmos-sdk/issues/127

**Comment by jbowen93** [comment]
@Manav-Aggarwal Please link to Tendermint proto changes.

**Comment by Manav-Aggarwal** [comment]
Handled by: https://github.com/celestiaorg/rollmint/pull/567
