### ISSUE TITLE
Maintain a blacklist of malicious peers 

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/rollmint#386]
Optimint nodes should maintain a blacklist of peers that they have determined are acting malicious. Nodes should sever their peering connections with malicious nodes and refuse to rebroadcast any messages they receive from these nodes.

We should consider if there is value in having a set of "blacklist seed nodes" which maintain a blacklist they can share with new nodes joining the p2p network. 

-----
Subtasks:
- [ ] Use libp2p.ConnectionGater to limit connections
- [ ] Implement [`datastore.Datastore`](https://pkg.go.dev/github.com/ipfs/go-datastore#Datastore) interface 
- [ ] Add configuration option/param to block peer/IP
- [ ] Make it possible to unblock blacklisted peer/IP

**Comment by tzdybal** [comment]
To actually implement blacklisting we should use [ConnectionGater](https://pkg.go.dev/github.com/libp2p/go-libp2p@v0.23.2/core/connmgr#ConnectionGater) interface. Probably, [default implementation](https://pkg.go.dev/github.com/libp2p/go-libp2p/p2p/net/conngater#BasicConnectionGater) will be sufficient. 

Gater has to be passed as an option here: https://github.com/celestiaorg/rollmint/blob/cc0a2950ea752b8905fb35062069a951c99ef115/p2p/client.go#L230

**Comment by randomshinichi** [comment]
Looks like an issue with meat, I'll take it on
