### ISSUE TITLE
Introduce const for namespace size

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#411]
> Ideally, that 8 would be a const or rather using an existing const.

_Originally posted by @liamsi in https://github.com/celestiaorg/optimint/pull/399#discussion_r881742416_

Currently `8` is hardcoded in many places, and it's used as namespace size. Const should be extracted and used **everywhere**.

**Comment by jbowen93** [comment]
I understand the desire to avoid "magic numbers" but to play devil's advocate the `[8]byte` is probably more readable than `[nsIDLength]byte` or whatever name we use.

Of course if it every changes it's annoying to have to change it everywhere.

**Comment by tzdybal** [comment]
Maybe introducing a type, like `namespace.ID` would be better.

**Comment by tzdybal** [comment]
I think that `types` package is the right place, as this is used across the repo. I'm not sure about the name TBH. Maybe `types.NID`?
