### ISSUE TITLE
Fraud proof generation

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#6]
Full nodes are responsible for creating and propagating fraud proofs.

To be able to produce fraud proofs, we need to have SMT state commitments in cosmos-sdk (as described in [ADR-040](https://github.com/cosmos/cosmos-sdk/pull/8430)), and execution trace added to blocks.

**Comment by liamsi** [comment]
I think this issue description should be updated to reflect the pivot in priorities. cc @tzdybal @mattdf @adlerjohn

**Comment by adlerjohn** [comment]
Short: fraud proofs don't require ISRs, and can instead be done on a per-block basis, where each block contains a single tx.

**Comment by tzdybal** [comment]
Closed by #567.
