### ISSUE TITLE
Implement Header interface

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#641]
Implement the Header interface:
```go
// Header abstracts all methods required to perform header sync.
type Header interface {
	// New creates new instance of a header.
	New() Header
	// Hash returns hash of a header.
	Hash() Hash
	// Height returns the height of a header.
	Height() int64
	// LastHeader returns the hash of last header before this header (aka. previous header hash).
	LastHeader() Hash
	// Time returns time when header was created.
	Time() time.Time
	// IsRecent checks if header is recent against the given blockTime.
	IsRecent(duration time.Duration) bool
	// IsExpired checks if header is expired against trusting period.
	IsExpired() bool
	// VerifyAdjacent validates adjacent untrusted header against trusted header.
	VerifyAdjacent(Header) error
	// VerifyNonAdjacent validates non-adjacent untrusted header against trusted header.
	VerifyNonAdjacent(Header) error
	// Verify performs basic verification of untrusted header.
	Verify(Header) error
	// Validate performs basic validation to check for missed/incorrect fields.
	Validate() error

	encoding.BinaryMarshaler
	encoding.BinaryUnmarshaler
}
```

**Comment by gupadhyaya** [comment]
1. @tzdybal could you add some details as to why this is needed? I am missing the full context. 
2. some functions in Header interface already exists, e.g., `Hash()` in `types/hashing.go` and `MarshalBinary & UnmarshalBinary` in `types/serialization.go`. we don't need to move them under the same file right? we can simply implement rest of the functions in e.g., `header.go` under `types/header.go`?
3. where can i read the specification for some of the functions like `Verify`, `VerifyAdjacent`, etc? or could you add some clarifying details as what they are expected to do?

**Comment by tzdybal** [comment]
> 1. @tzdybal could you add some details as to why this is needed? I am missing the full context.

This `Header` interface is a generic interface that will be used by https://github.com/celestiaorg/go-header/. This will be the common logic used to execute header sync in both celestia-node and rollmint light clients. Additionally we will need this interface to allow different headers implementations (for optimistic rollups, ZK rollups), and to enable users creating their own implementations. 

>     2. some functions in Header interface already exists, e.g., `Hash()` in `types/hashing.go` and `MarshalBinary & UnmarshalBinary` in `types/serialization.go`. we don't need to move them under the same file right? we can simply implement rest of the functions in e.g., `header.go` under `types/header.go`?

Yes. We can simply implement the rest of the functions, without moving the existing ones. Note: I think that `ValidateBasic` can be simpy renamed to `Validate`.  

>     3. where can i read the specification for some of the functions like `Verify`, `VerifyAdjacent`, etc? or could you add some clarifying details as what they are expected to do?

Unfortunately there is no documentation yet. The best you can get is to look at implementation in node - and at the same time, I'll work on creating godocs for all those methods.
https://github.com/celestiaorg/celestia-node/blob/da4f54bca1bfef86f53880ced569d37ffb4b8b84/header/verify.go#L36
https://github.com/celestiaorg/celestia-node/blob/da4f54bca1bfef86f53880ced569d37ffb4b8b84/header/verify.go#L51

**Comment by gupadhyaya** [comment]
@tzdybal 
1) `New` should create empty `Header` or something similar to clone?
2) `Header` type has fileds `Height` and `Time`, are the interface methods necessary? Also it doesn't allow duplicate field and interface method

**Comment by gupadhyaya** [comment]
also, `VerifyNonAdjacent` requires `Ensure that untrusted commit has enough of trusted commit's power.` without the store, it is not possible to get access to `ValidatorSet` or `Commits`. any ideas on how to cover this? @tzdybal

**Comment by tzdybal** [comment]
1. `New` should create new instance of concrete type implementing the interface. Context: when deserializing we need actual object of given type, like:
```go
var obj H
obj.UnmarshalBinary(data)
```
where `H` is generic type of `header.Header` interface. This won't work unfortunately, as default value for pointers is `nil` so deserialization will panic. And most probably interface will be implemented for pointer receiver.
The "hack" to mitigate this without using reflection, with construct like:
```go
var empty H
obj := empty.New()
obj.UnmarshalBinary(data)
```

2. Yes, right now we have `Height` and `Time` as fields, but we need to refactor this. Because interfaces cannot define fields, and we need an universal method of accessing `Height` and `Time` in header library.

3. Sorry for that - I just copy-pasted the comment from Node implementation, and it makes no sense :facepalm: This method definitely work without accessing store.

**Comment by gupadhyaya** [comment]
@tzdybal few more questions:
1) https://github.com/celestiaorg/go-header seems like not ready, should the rollmint repo add go-header as dependency and use Header interface definition? The `Hash` type seems to be missing. 
2) Throughout rollmint `[32]byte` is used where as celestia-core uses `tmbytes.HexBytes` and the generic header interface planning to use a new type [`Hash`](https://github.com/celestiaorg/celestia-node/blob/7b03f25a5502772b272a373a6f57647dd05419ad/libs/header/hash.go). May be we should make these uniform across?
3) I am still confused about the `New` method. Should it not return an empty instance of https://github.com/celestiaorg/rollmint/blob/main/types/block.go#L10?
I have a draft PR above and could you let me know if the direction i am taking is correct?

**Comment by tzdybal** [comment]
1. Yes - current go-header is out-of-date. After merging https://github.com/celestiaorg/celestia-node/pull/1304, I'll extract the code from celestia-node to go-header (again), and we'll be able to add it as dependency for rollmint.
2. My PR replaces `HexBytes` in node, as it's completely unnecessary. For now, you can copy the hash definition, just like you copied `Header` interface. We'll refactor this when go-header is ready.
3. Yes it should return empty instance of our `Header`, as you mentioned :+1:

**Comment by S1nus** [comment]
> also, VerifyNonAdjacent requires Ensure that untrusted commit has enough of trusted commit's power. without the store, it is not possible to get access to ValidatorSet or Commits. any ideas on how to cover this?

you could give it the validator set as an argument along with a merkle proof to the previous header's root
