### ISSUE TITLE
Extract `Node` interface from existing code

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#650]
- [x] Rename `node.Node` to `node.FullNode`
- [x] Create `node.Node` interface by extracting all existing public functions of `node.FullNode`
- [x] Create `node.newFullNode` function and move `node.NewNode` functionality there
- [x] Modify `node.NewNode` to just call `node.newFullNode` (this will be changed later, see: #651).
- [x] Consider moving `noode.FullNode` to `node/full_node.go`

**Comment by S1nus** [comment]
https://github.com/celestiaorg/rollmint/pull/646

**Comment by tzdybal** [comment]
We decided not to proceed with this approach.
