### ISSUE TITLE
Create stub of `LightNode` implementation

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#651]
Depends on #642, #650.

- [ ] Create `LightNode` struct
- [ ] Create stub/empty implementation of all `Node` methods
- [ ] Add dispatching logic to `node.NewNode` to return `FullNode` or `LightNode` depending on `config.Light` option.

**Comment by S1nus** [comment]
https://github.com/celestiaorg/rollmint/pull/646

**Comment by tzdybal** [comment]
We decided not to proceed with this approach.
