### ISSUE TITLE
Check Compatibilty with Tendermint and decide if to use int64 or uint64 for block height

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/rollmint#679]
Rollmint has an inconsistency what type it uses for block height.
[Examples](https://github.com/celestiaorg/rollmint/search?q=height+int64) for int64, [Examples](https://github.com/celestiaorg/rollmint/search?q=height+uint64) for unit64 .

It is caused by "compatibility" issues with Tendermint. We need to decide which type to use.

Discussion originally started in https://github.com/celestiaorg/rollmint/pull/665#discussion_r1060635274_

**Comment by tzdybal** [comment]
Uh, oh, I duplicated it in #688, but there's also a bit wider context.
