### ISSUE TITLE
Use consistent type for all hash fields in Header

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/rollmint#689]
Original implementation used `[32]byte` to represent hashes. [go-header](https://github.com/celestiaorg/go-header) library defines `Hash` which is an alias for `[]byte`. 
#685 changes only selected fields to new type, to ensure compatibility with go-header. We should refactor all the other `Hash` related fields. It might also be reasonable to alias `header.Hash` in `types` package, to use `type.Hash` instead of `header.Hash`.

**Comment by nashqueue** [comment]
Relevant comment to this issue: https://github.com/celestiaorg/rollmint/pull/685#discussion_r1072123659
